### ISSUE TITLE
Uno 1.1.2 is incompatible with Flutter 3.3.10

### ISSUE THREAD

**Issue by jttuboi** [Flutterando/uno#28]
Please, look if is possible to downgrade the package dependencies to:
```yaml
  characters: ">=1.2.1 <2.0.0"
  meta: ">=1.8.0 <2.0.0"
  path: ">=1.8.2 <2.0.0"
```
For now, I can't upgrade to Flutter 3.7.x, so I'm still using 3.3.10 and these messages show when I try to use Uno 1.1.2:

<img width="789" alt="image" src="https://user-images.githubusercontent.com/376856/222220942-640bb67b-08ef-4ca7-95fe-778ec2e7c6bb.png">

after I force to downgrade meta to 1.8.0 inside of local package of uno 1.1.2:

<img width="787" alt="image" src="https://user-images.githubusercontent.com/376856/222221207-feca02be-77aa-4702-b14a-71418011e0cd.png">

and after I force to downgrade characters to 1.2.1 inside of local package of uno 1.1.2:

<img width="791" alt="image" src="https://user-images.githubusercontent.com/376856/222221529-f31c4d60-8d82-44e6-84dd-ab73135f0db2.png">

and after this, flutter pub get doesn't complain anymore.

I haven't checked if these downgrades affect the last fixes, but these package upgrade is incompatible with flutter 3.3.10.

**Comment by jacobaraujo7** [comment]
Gotcha!

**Comment by jacobaraujo7** [comment]
Added in pubspec.yaml
```yaml
  characters: ">=1.2.1 <2.0.0"
  meta: ">=1.8.0 <2.0.0"
  path: ">=1.8.2 <2.0.0"
```
